### ISSUE TITLE
Lista zadań

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania-exercises#2]
Zebrałem listę zadań za pomocą otwierania ramek w nowych oknach i takiej komendy:
```js
console.log(([...document.getElementsByTagName('input')].filter((e)=>e.name=='zad').map((e)=>e.value)).join('\n'))
```

Przede wszystkim najważniejsze jest to, żeby lista była spójna, jednolita i żeby dało się ją wklepać do jakiegoś skryptu.
Poniżej zrobiłem podziałem na sekcje (po `-`) i podsekcje (po `+`).
Do przejrzenia, poprawienia nazw i skonsultowania, trzeba znaleźć duplikaty i ostatecznie rozpisać jako komendy, np:

```
mkdir kinematyka
mkdir kinematyka/mechanika
touch kinematyka/mechanika/pociągi-dwa
mkdir "gdziekolwiek indziej"
ln -s ../kinematyka/mechanika/pociągi-dwa "gdziekolwiek indziej/pociągi-dwa"
```

<details>
<summary>cała lista zadań (klik)</summary>

```
-kinematyka
+mechanika
Pociągi dwa 2
Czerpak 1
Łódka2.
Spotkanie2
Tramwaj
Samochody
Dwa ciała
Wektory
Most
Samolot
Statek
Zawody
Rzeka
Motorówka
Kajak
Przystanie
Biegacz
Pocisk
Lufa
Samochód
Krążek hokejowy
Kula
Wysokosc
Studnia
Ciało
Motocykl
Ciągnik
Karuzela
Kamień
Autobus
Ciało 2
Równik
Tarcza
Wskazówki
Przekładnia
Kula
Pręt
Wskazówki 2
+dynamika
Bloczki 1
Bloczki 2
Bloczki 3
Bloczki 4
Pojedynczy bloczek
Pojedynczy bloczek 2
Wagon
Sanki
Droga hamowania
+rzuty
Studnia
Pocisk 1
Pocisk 2
Piłka 1
Piłka 2
Kamień 1
Kamień 2
Kamyczek
Kula karabinowa
Piłeczka
Prędkość
+ped
1.Lodołamacz(2.40)
2.Urobek(2.41)
3.Szalka
4.Kulki
5.Bloczek
6.Drewniana kula
7.Ciśnienie
8.Wagon kolejowy
9.Samochód
10.Pocisk
11.Pociąg
12.Piłka
+tarcie
Równia 1
Równia 2
Równia 3
Równia 4
Sanki 1
Sanki 2
Dwie powierzchnie
Klocek na równi
Samochód 1
Samochód 2
Platforma
Wirownica
Klocek na stole
Krążek
Klocki
Klocki 2
Klocki 3
Wózek
Wózek 2
+siły bezwładności
Stożek
+Praca moc energia
Samochód
Sanki
Parowóz
Kula
Dwa ciała
Zsuwanie
Klocek
Zderzenie 1
Zderzenie 2
Zderzenie 3
Równia 1
Równia 2
Równia 3
Stosunek energii
Słup telegraficzny
Ciężarówka
Kamień
Walec
Pocisk
Obciążnik na równi
+bryła sztywna
Kula 1
Pręt 1
Rura grubościenna
Pręt 2
Walec 1
Walec 2
Walec 3
Kwadrat 1
Kwadrat 2
Kwadrat 3
Bryła 1
Bryła 2
Tarcza 1
Elipsa
Krążki
Koło zamachowe
+ciała stałe
Szeregowo
Równolegle
Gumka
Drut ołowiany
Wirujący pręt
Pręt ołowiany
Dwa pręty
Sześcian
Wydłużenie pręta
Stalowy drut
Stalowy drut 2
+ciecze
RzutCialaDoCieczy
CisnienieDwuCieczy
U-rurka
U-rurka2
U-rurka3
Gęstość oleju
L-rurka
Kra
Statek
-grawitacja
+prawo ciążenia
Lina Ziemia Księżyc
Natężenie zerowe
Planetoida
+natężenie
Natężenie 2 ciał
Potencjał 2 ciał
Gwiazda i planeta
Księżyc
W górach
Trzy masy
Natężenie trójkąt
Potencjał trójkąt
Stacja kosmiczna
Planeta
Prędkość księżyca
Masa gwiazdy
+energia
Dwie kule
Tunel
+potencjał
+prędkości kosmiczne
+prawa Keplera
Jowisz
Kometa Halley'a
Prędkość komety
-drgania
+harmoniczne
Wahadło Foucaulta
Odważnik
Energia
Wahadło 1
Wahadło 2
U-rurka
Samochód
Wagon
Punkt 1
Punkt 2
Punkt 3
+tłumione
+wymuszone
+rezonans
Wahadło Foucaulta
-fale
+równanie falowe
Fala płaska
Dwa punkty
+akustyka
Dwa dźwięki
Jeden dźwięk
Próg słyszalności
Zmiana
Doppler1
Doppler 2
Doppler 3
Doppler 4
Syrena
Głośnik
Gwizdek
Źródło1
Źródło2
Samochód1
Samochód2
Biegacz
Maszyny
-termodynamika
+energia temperatura
Zero bezwzględne
Temperatura azotu
Prędkość tlenu
Balon
+bilans
Kawa z mlekiem
Kubki z wodą
Dwie wody
Trzy wody
Napój z lodem
+przewodnictwo cieplne
Domek
+Równanie Clapeyrona
Tlen
Azot
Gaz w pojemniku
Zbiornik z gazem
Wysokość
Butla
Naczynia połączone
Pęcherzyk
Kula
Odległości
Azot2
Temperatura
Energia
Zbiorniki
Naczynia2
+Przemiany
Rurka Meldego
Pompka
Naczynie
Strzykawka
Cylinder
Pionowa rurka
Zbiornik
Cylinder2
Gaz 2-atom.
Zad. 618
Wykres-620
Dwa naczynia
+Cykle
Sprawność 1
Sprawność 2
Sprawność 3
Idealny 1
Idealny 2
Idealny 3
Idealny 4
Dwa Carnoty
-elektrostatyka
+pole elektro
Wahadło
+pojemność
Dielektryk 1
Dielektryk 2
Połączone kule
Połączone kondensatory
+energia
Energia 1
Energia 2
+ruch ład
-prąd
+opory zastępcze
Szeregowe żarówki
Równoległe żarówki
Pięć oporników
Drabina oporników
+prąd stały
Prędkość unoszenia
Grzałki
Gotowanie
+obwody
Dwie żarówki
Moc opornika
Prawa Kirchhoffa
-magnetyzm
+natężenie pola
Kierunek pola
+Siła elektro
Przewodniki
Szyny
+siła Lorentza
Cyklotron
Energia cząstki
Promień okręgu
Stosunek promieni
Deuteron i proton
Różnica potencjałów protonu
Promień okręgu dla protonu
Skok śruby
Prędkośc protonu
+zjawisko Halla
-indukcja
+indukcja // DUP
Ramka
Samolot
+prąd zmienny
Natężenie 1
Natężenie 2
+obwody rlc
-optyka
+zwierciadła
Teleskop
Zwierciadło sferyczne
Teleskop zwierciadlany
+pryzmat
+soczewki
Zdjęcie
Soczewka
Dwa źródła światła
Dwuwypukła soczewka
Układ optyczny
Pręt
Wiązka promieni
+polaryzacja
Płytka równoległościenna
Kat Brewstera
-fiz wsp
+atom
+foto elektr
Platyna
Katoda
+ciało doskonale czarne
Lot do gwiazd
Adam i Ewa
Mezony
```

</details>

**Comment by MichalTheProgrammer** [comment]
```
---
- kinematyka:
  - mechanika:
    - Pociągi dwa 2
    - Czerpak 1
    - Łódka 2
    - Spotkanie 2
    - Tramwaj
    - Samochody
    - Dwa ciała
    - Wektory
    - Most
    - Samolot
    - Statek
    - Zawody
    - Rzeka
    - Motorówka
    - Kajak
    - Przystanie
    - Biegacz
    - Pocisk
    - Lufa
    - Samochód
    - Krążek hokejowy
    - Kula
    - Wysokość
    - Studnia
    - Ciało
    - Motocykl
    - Ciągnik
    - Karuzela
    - Kamień
    - Autobus
    - Ciało 2
    - Równik
    - Tarcza
    - Wskazówki
    - Przekładnia
    - Kula
    - Pręt
    - Wskazówki 2
  - dynamika:
    - Bloczki 1
    - Bloczki 2
    - Bloczki 3
    - Bloczki 4
    - Pojedynczy bloczek
    - Pojedynczy bloczek 2
    - Wagon
    - Sanki
    - Droga hamowania
  - rzuty:
    - Studnia
    - Pocisk 1
    - Pocisk 2
    - Piłka 1
    - Piłka 2
    - Kamień 1
    - Kamień 2
    - Kamyczek
    - Kula karabinowa
    - Piłeczka
    - Prędkość
  - pęd:
    - Lodołamacz (2.40)
    - Urobek (2.41)
    - Szalka
    - Kulki
    - Bloczek
    - Drewniana kula
    - Ciśnienie
    - Wagon kolejowy
    - Samochód
    - Pocisk
    - Pociąg
    - Piłka
  - tarcie:
    - Równia 1
    - Równia 2
    - Równia 3
    - Równia 4
    - Sanki 1
    - Sanki 2
    - Dwie powierzchnie
    - Klocek na równi
    - Samochód 1
    - Samochód 2
    - Platforma
    - Wirownica
    - Klocek na stole
    - Krążek
    - Klocki
    - Klocki 2
    - Klocki 3
    - Wózek
    - Wózek 2
  - siły bezwładności:
    - Stożek
  - Praca moc energia:
    - Samochód
    - Sanki
    - Parowóz
    - Kula
    - Dwa ciała
    - Zsuwanie
    - Klocek
    - Zderzenie 1
    - Zderzenie 2
    - Zderzenie 3
    - Równia 1
    - Równia 2
    - Równia 3
    - Stosunek energii
    - Słup telegraficzny
    - Ciężarówka
    - Kamień
    - Walec
    - Pocisk
    - Obciążnik na równi
  - bryła sztywna:
    - Kula 1
    - Pręt 1
    - Rura grubościenna
    - Pręt 2
    - Walec 1
    - Walec 2
    - Walec 3
    - Kwadrat 1
    - Kwadrat 2
    - Kwadrat 3
    - Bryła 1
    - Bryła 2
    - Tarcza 1
    - Elipsa
    - Krążki
    - Koło zamachowe
  - ciała stałe:
    - Szeregowo
    - Równolegle
    - Gumka
    - Drut ołowiany
    - Wirujący pręt
    - Pręt ołowiany
    - Dwa pręty
    - Sześcian
    - Wydłużenie pręta
    - Stalowy drut
    - Stalowy drut 2
  - ciecze:
    - Rzut Ciał Do Cieczy
    - Ciśnienie DwuCieczy
    - U-rurka
    - U-rurka2
    - U-rurka3
    - Gęstość oleju
    - L-rurka
    - Kra
    - Statek
- grawitacja:
  - prawo ciążenia:
    - Lina Ziemia Księżyc
    - Natężenie zerowe
    - Planetoida
  - natężenie:
    - Natężenie 2 ciał
    - Potencjał 2 ciał
    - Gwiazda i planeta
    - Księżyc
    - W górach
    - Trzy masy
    - Natężenie trójkąt
    - Potencjał trójkąt
    - Stacja kosmiczna
    - Planeta
    - Prędkość księżyca
    - Masa gwiazdy
  - energia:
    - Dwie kule
    - Tunel
  - potencjał:
  - prędkości kosmiczne:
  - prawa Keplera:
    - Jowisz
    - Kometa Halley'a
    - Prędkość komety
- drgania:
  - harmoniczne:
    - Wahadło Foucaulta
    - Odważnik
    - Energia
    - Wahadło 1
    - Wahadło 2
    - U-rurka
    - Samochód
    - Wagon
    - Punkt 1
    - Punkt 2
    - Punkt 3
  - tłumione:
  - wymuszone:
  - rezonans:
    - Wahadło Foucaulta
  - fale:
  - równanie falowe:
    - Fala płaska
    - Dwa punkty
  - akustyka:
    - Dwa dźwięki
    - Jeden dźwięk
    - Próg słyszalności
    - Zmiana
    - Doppler 1
    - Doppler 2
    - Doppler 3
    - Doppler 4
    - Syrena
    - Głośnik
    - Gwizdek
    - Źródło 1
    - Źródło 2
    - Samochód 1
    - Samochód 2
    - Biegacz
    - Maszyny
- termodynamika:
  - energia temperatura:
    - Zero bezwzględne
    - Temperatura azotu
    - Prędkość tlenu
    - Balon
  - bilans:
    - Kawa z mlekiem
    - Kubki z wodą
    - Dwie wody
    - Trzy wody
    - Napój z lodem
  - przewodnictwo cieplne:
    - Domek
  - Równanie Clapeyrona:
    - Tlen
    - Azot
    - Gaz w pojemniku
    - Zbiornik z gazem
    - Wysokość
    - Butla
    - Naczynia połączone
    - Pęcherzyk
    - Kula
    - Odległości
    - Azot 2
    - Temperatura
    - Energia
    - Zbiorniki
    - Naczynia 2
  - Przemiany:
    - Rurka Meldego
    - Pompka
    - Naczynie
    - Strzykawka
    - Cylinder
    - Pionowa rurka
    - Zbiornik
    - Cylinder2
    - Gaz 2-atom
    - Zad. 618
    - Wykres-620
    - Dwa naczynia
  - Cykle:
    - Sprawność 1
    - Sprawność 2
    - Sprawność 3
    - Idealny 1
    - Idealny 2
    - Idealny 3
    - Idealny 4
    - Dwa Carnoty
- elektrostatyka:
  - pole elektro:
    - Wahadło
  - pojemność:
    - Dielektryk 1
    - Dielektryk 2
    - Połączone kule
    - Połączone kondensatory
  - energia:
    - Energia 1
    - Energia 2
  - ruch ład:
- prąd:
  - opory zastępcze:
    - Szeregowe żarówki
    - Równoległe żarówki
    - Pięć oporników
    - Drabina oporników
  - prąd stały:
    - Prędkość unoszenia
    - Grzałki
    - Gotowanie
  - obwody:
    - Dwie żarówki
    - Moc opornika
    - Prawa Kirchhoffa
- magnetyzm:
  - natężenie pola:
    - Kierunek pola
  - Siła elektro:
    - Przewodniki
    - Szyny
  - siła Lorentza:
    - Cyklotron
    - Energia cząstki
    - Promień okręgu
    - Stosunek promieni
    - Deuteron i proton
    - Różnica potencjałów protonu
    - Promień okręgu dla protonu
    - Skok śruby
    - Prędkość protonu
  - zjawisko Halla:
- indukcja:
  - indukcja // DUP:
    - Ramka
    - Samolot
  - prąd zmienny:
    - Natężenie 1
    - Natężenie 2
  - obwody rlc:
- optyka:
  - zwierciadła:
    - Teleskop
    - Zwierciadło sferyczne
    - Teleskop zwierciadlany
  - pryzmat:
  - soczewki:
    - Zdjęcie
    - Soczewka
    - Dwa źródła światła
    - Dwuwypukła soczewka
    - Układ optyczny
    - Pręt
    - Wiązka promieni
  - polaryzacja:
    - Płytka równoległościenna
    - Kat Brewstera
- fiz wsp:
  - atom:
  - foto elektr:
    - Platyna
    - Katoda
  - ciało doskonale czarne:
    - Lot do gwiazd
    - Adam i Ewa
    - Mezony
...
```
